# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/data/data/Code/Python/LadaDetail/forms/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_cars = QtWidgets.QWidget()
        self.page_cars.setObjectName("page_cars")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_cars)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.page_cars)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.carAddButton = QtWidgets.QPushButton(self.groupBox)
        self.carAddButton.setObjectName("carAddButton")
        self.gridLayout.addWidget(self.carAddButton, 1, 0, 1, 1)
        self.carDeleteButton = QtWidgets.QPushButton(self.groupBox)
        self.carDeleteButton.setObjectName("carDeleteButton")
        self.gridLayout.addWidget(self.carDeleteButton, 1, 1, 1, 1)
        self.carListView = QtWidgets.QListView(self.groupBox)
        self.carListView.setObjectName("carListView")
        self.gridLayout.addWidget(self.carListView, 0, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_cars)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formStack = QtWidgets.QStackedWidget(self.groupBox_2)
        self.formStack.setObjectName("formStack")
        self.formReadPage = QtWidgets.QWidget()
        self.formReadPage.setObjectName("formReadPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.formReadPage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.carEditButton = QtWidgets.QPushButton(self.formReadPage)
        self.carEditButton.setEnabled(False)
        self.carEditButton.setMinimumSize(QtCore.QSize(97, 0))
        self.carEditButton.setObjectName("carEditButton")
        self.gridLayout_2.addWidget(self.carEditButton, 3, 3, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.formReadPage)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.carNameLabel = QtWidgets.QLabel(self.formReadPage)
        self.carNameLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.carNameLabel.setText("")
        self.carNameLabel.setObjectName("carNameLabel")
        self.gridLayout_3.addWidget(self.carNameLabel, 0, 1, 1, 1)
        self.carDescriptionLabel = QtWidgets.QLabel(self.formReadPage)
        self.carDescriptionLabel.setText("")
        self.carDescriptionLabel.setWordWrap(True)
        self.carDescriptionLabel.setObjectName("carDescriptionLabel")
        self.gridLayout_3.addWidget(self.carDescriptionLabel, 2, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formReadPage)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 2, 1)
        self.carPhotoLabel = QtWidgets.QLabel(self.formReadPage)
        self.carPhotoLabel.setMinimumSize(QtCore.QSize(160, 160))
        self.carPhotoLabel.setMaximumSize(QtCore.QSize(160, 160))
        self.carPhotoLabel.setStyleSheet("border: 1px solid;")
        self.carPhotoLabel.setText("")
        self.carPhotoLabel.setIndent(-1)
        self.carPhotoLabel.setObjectName("carPhotoLabel")
        self.gridLayout_2.addWidget(self.carPhotoLabel, 0, 2, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 2)
        self.formStack.addWidget(self.formReadPage)
        self.formEditPage = QtWidgets.QWidget()
        self.formEditPage.setObjectName("formEditPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.formEditPage)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.carSaveButton = QtWidgets.QPushButton(self.formEditPage)
        self.carSaveButton.setObjectName("carSaveButton")
        self.gridLayout_5.addWidget(self.carSaveButton, 4, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 4, 0, 1, 3)
        self.carCancelButton = QtWidgets.QPushButton(self.formEditPage)
        self.carCancelButton.setObjectName("carCancelButton")
        self.gridLayout_5.addWidget(self.carCancelButton, 4, 4, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.carNameEdit = QtWidgets.QLineEdit(self.formEditPage)
        self.carNameEdit.setObjectName("carNameEdit")
        self.gridLayout_4.addWidget(self.carNameEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formEditPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.formEditPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.formEditPage)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 2, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 3, 1)
        self.carDeletePhotoButton = QtWidgets.QPushButton(self.formEditPage)
        self.carDeletePhotoButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.carDeletePhotoButton.setObjectName("carDeletePhotoButton")
        self.gridLayout_5.addWidget(self.carDeletePhotoButton, 1, 4, 1, 1)
        self.carBrowsePhotoButton = QtWidgets.QPushButton(self.formEditPage)
        self.carBrowsePhotoButton.setMinimumSize(QtCore.QSize(0, 0))
        self.carBrowsePhotoButton.setObjectName("carBrowsePhotoButton")
        self.gridLayout_5.addWidget(self.carBrowsePhotoButton, 1, 3, 1, 1)
        self.carPhotoLabel_2 = QtWidgets.QLabel(self.formEditPage)
        self.carPhotoLabel_2.setMinimumSize(QtCore.QSize(160, 160))
        self.carPhotoLabel_2.setMaximumSize(QtCore.QSize(160, 160))
        self.carPhotoLabel_2.setStyleSheet("border: 1px solid;")
        self.carPhotoLabel_2.setText("")
        self.carPhotoLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.carPhotoLabel_2.setIndent(-1)
        self.carPhotoLabel_2.setObjectName("carPhotoLabel_2")
        self.gridLayout_5.addWidget(self.carPhotoLabel_2, 0, 3, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 1, 2, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 2, 1, 1, 4)
        spacerItem7 = QtWidgets.QSpacerItem(341, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem7, 3, 0, 1, 5)
        self.formStack.addWidget(self.formEditPage)
        self.horizontalLayout_2.addWidget(self.formStack)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.page_cars)
        self.page_clients = QtWidgets.QWidget()
        self.page_clients.setObjectName("page_clients")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_clients)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_clients)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.clientListView = QtWidgets.QListView(self.groupBox_3)
        self.clientListView.setObjectName("clientListView")
        self.gridLayout_6.addWidget(self.clientListView, 0, 0, 1, 2)
        self.clientAddButton = QtWidgets.QPushButton(self.groupBox_3)
        self.clientAddButton.setObjectName("clientAddButton")
        self.gridLayout_6.addWidget(self.clientAddButton, 1, 0, 1, 1)
        self.clientDeleteButton = QtWidgets.QPushButton(self.groupBox_3)
        self.clientDeleteButton.setEnabled(False)
        self.clientDeleteButton.setObjectName("clientDeleteButton")
        self.gridLayout_6.addWidget(self.clientDeleteButton, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_clients)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.clientStack = QtWidgets.QStackedWidget(self.groupBox_4)
        self.clientStack.setObjectName("clientStack")
        self.clientReadPage = QtWidgets.QWidget()
        self.clientReadPage.setObjectName("clientReadPage")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.clientReadPage)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem8, 2, 0, 1, 2)
        self.clientEditButton = QtWidgets.QPushButton(self.clientReadPage)
        self.clientEditButton.setEnabled(False)
        self.clientEditButton.setMinimumSize(QtCore.QSize(97, 0))
        self.clientEditButton.setObjectName("clientEditButton")
        self.gridLayout_7.addWidget(self.clientEditButton, 2, 2, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_5 = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.clientReadPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 7, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 6, 0, 1, 1)
        self.clientPassportLabel = QtWidgets.QLabel(self.clientReadPage)
        self.clientPassportLabel.setMinimumSize(QtCore.QSize(0, 190))
        self.clientPassportLabel.setStyleSheet("border: 1px solid;")
        self.clientPassportLabel.setText("")
        self.clientPassportLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.clientPassportLabel.setObjectName("clientPassportLabel")
        self.gridLayout_8.addWidget(self.clientPassportLabel, 8, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 3, 0, 1, 1)
        self.clientFirstnameLabel = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientFirstnameLabel.sizePolicy().hasHeightForWidth())
        self.clientFirstnameLabel.setSizePolicy(sizePolicy)
        self.clientFirstnameLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.clientFirstnameLabel.setStyleSheet("border: 1px solid;")
        self.clientFirstnameLabel.setText("")
        self.clientFirstnameLabel.setObjectName("clientFirstnameLabel")
        self.gridLayout_8.addWidget(self.clientFirstnameLabel, 1, 1, 1, 2)
        self.clientRegdateLabel = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientRegdateLabel.sizePolicy().hasHeightForWidth())
        self.clientRegdateLabel.setSizePolicy(sizePolicy)
        self.clientRegdateLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.clientRegdateLabel.setStyleSheet("border: 1px solid;")
        self.clientRegdateLabel.setText("")
        self.clientRegdateLabel.setObjectName("clientRegdateLabel")
        self.gridLayout_8.addWidget(self.clientRegdateLabel, 4, 1, 1, 2)
        self.clientPhoneLabel = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientPhoneLabel.sizePolicy().hasHeightForWidth())
        self.clientPhoneLabel.setSizePolicy(sizePolicy)
        self.clientPhoneLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.clientPhoneLabel.setStyleSheet("border: 1px solid;")
        self.clientPhoneLabel.setText("")
        self.clientPhoneLabel.setObjectName("clientPhoneLabel")
        self.gridLayout_8.addWidget(self.clientPhoneLabel, 6, 1, 1, 2)
        self.label_69 = QtWidgets.QLabel(self.clientReadPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_8.addWidget(self.label_69, 5, 0, 1, 1)
        self.clientMiddlenameLabel = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientMiddlenameLabel.sizePolicy().hasHeightForWidth())
        self.clientMiddlenameLabel.setSizePolicy(sizePolicy)
        self.clientMiddlenameLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.clientMiddlenameLabel.setStyleSheet("border: 1px solid;")
        self.clientMiddlenameLabel.setText("")
        self.clientMiddlenameLabel.setObjectName("clientMiddlenameLabel")
        self.gridLayout_8.addWidget(self.clientMiddlenameLabel, 2, 1, 1, 2)
        self.clientBirthdateLabel = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientBirthdateLabel.sizePolicy().hasHeightForWidth())
        self.clientBirthdateLabel.setSizePolicy(sizePolicy)
        self.clientBirthdateLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.clientBirthdateLabel.setStyleSheet("border: 1px solid;")
        self.clientBirthdateLabel.setText("")
        self.clientBirthdateLabel.setWordWrap(True)
        self.clientBirthdateLabel.setObjectName("clientBirthdateLabel")
        self.gridLayout_8.addWidget(self.clientBirthdateLabel, 3, 1, 1, 2)
        self.clientLastnameLabel = QtWidgets.QLabel(self.clientReadPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientLastnameLabel.sizePolicy().hasHeightForWidth())
        self.clientLastnameLabel.setSizePolicy(sizePolicy)
        self.clientLastnameLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.clientLastnameLabel.setStyleSheet("border: 1px solid;")
        self.clientLastnameLabel.setText("")
        self.clientLastnameLabel.setObjectName("clientLastnameLabel")
        self.gridLayout_8.addWidget(self.clientLastnameLabel, 0, 1, 1, 2)
        self.clientEmailLabel = QtWidgets.QLabel(self.clientReadPage)
        self.clientEmailLabel.setStyleSheet("border: 1px solid;")
        self.clientEmailLabel.setText("")
        self.clientEmailLabel.setObjectName("clientEmailLabel")
        self.gridLayout_8.addWidget(self.clientEmailLabel, 5, 1, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 0, 2, 3)
        self.clientStack.addWidget(self.clientReadPage)
        self.clientWritePage = QtWidgets.QWidget()
        self.clientWritePage.setObjectName("clientWritePage")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.clientWritePage)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.clientSaveButton = QtWidgets.QPushButton(self.clientWritePage)
        self.clientSaveButton.setObjectName("clientSaveButton")
        self.gridLayout_9.addWidget(self.clientSaveButton, 4, 2, 1, 1)
        self.clientCancelButton = QtWidgets.QPushButton(self.clientWritePage)
        self.clientCancelButton.setObjectName("clientCancelButton")
        self.gridLayout_9.addWidget(self.clientCancelButton, 4, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 4, 0, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.clientWritePage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 2, 0, 1, 1)
        self.clientPassportEdit = QtWidgets.QPlainTextEdit(self.clientWritePage)
        self.clientPassportEdit.setObjectName("clientPassportEdit")
        self.gridLayout_9.addWidget(self.clientPassportEdit, 3, 0, 1, 4)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.clientFirstnameEdit = QtWidgets.QLineEdit(self.clientWritePage)
        self.clientFirstnameEdit.setObjectName("clientFirstnameEdit")
        self.gridLayout_10.addWidget(self.clientFirstnameEdit, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.clientWritePage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.clientWritePage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 1, 0, 1, 1)
        self.clientLastnameEdit = QtWidgets.QLineEdit(self.clientWritePage)
        self.clientLastnameEdit.setObjectName("clientLastnameEdit")
        self.gridLayout_10.addWidget(self.clientLastnameEdit, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.clientWritePage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.clientWritePage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.clientWritePage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 6, 0, 1, 1)
        self.clientMiddlenameEdit = QtWidgets.QLineEdit(self.clientWritePage)
        self.clientMiddlenameEdit.setObjectName("clientMiddlenameEdit")
        self.gridLayout_10.addWidget(self.clientMiddlenameEdit, 2, 1, 1, 1)
        self.clientPhoneEdit = QtWidgets.QLineEdit(self.clientWritePage)
        self.clientPhoneEdit.setObjectName("clientPhoneEdit")
        self.gridLayout_10.addWidget(self.clientPhoneEdit, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.clientWritePage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 4, 0, 1, 1)
        self.clientBirthdateEdit = QtWidgets.QDateEdit(self.clientWritePage)
        self.clientBirthdateEdit.setCalendarPopup(True)
        self.clientBirthdateEdit.setObjectName("clientBirthdateEdit")
        self.gridLayout_10.addWidget(self.clientBirthdateEdit, 3, 1, 1, 1)
        self.clientRegdateEdit = QtWidgets.QDateEdit(self.clientWritePage)
        self.clientRegdateEdit.setCalendarPopup(True)
        self.clientRegdateEdit.setObjectName("clientRegdateEdit")
        self.gridLayout_10.addWidget(self.clientRegdateEdit, 4, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.clientWritePage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_10.addWidget(self.label_70, 5, 0, 1, 1)
        self.clientEmailEdit = QtWidgets.QLineEdit(self.clientWritePage)
        self.clientEmailEdit.setObjectName("clientEmailEdit")
        self.gridLayout_10.addWidget(self.clientEmailEdit, 5, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 0, 0, 2, 4)
        self.clientStack.addWidget(self.clientWritePage)
        self.gridLayout_11.addWidget(self.clientStack, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.stackedWidget.addWidget(self.page_clients)
        self.page_employees = QtWidgets.QWidget()
        self.page_employees.setObjectName("page_employees")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_employees)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_employees)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.clientAddButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.clientAddButton_2.setObjectName("clientAddButton_2")
        self.gridLayout_12.addWidget(self.clientAddButton_2, 1, 0, 1, 1)
        self.clientDeleteButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.clientDeleteButton_2.setObjectName("clientDeleteButton_2")
        self.gridLayout_12.addWidget(self.clientDeleteButton_2, 1, 1, 1, 1)
        self.clientListView_2 = QtWidgets.QListView(self.groupBox_5)
        self.clientListView_2.setObjectName("clientListView_2")
        self.gridLayout_12.addWidget(self.clientListView_2, 0, 0, 1, 2)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_employees)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.formStack_3 = QtWidgets.QStackedWidget(self.groupBox_6)
        self.formStack_3.setObjectName("formStack_3")
        self.formReadPage_3 = QtWidgets.QWidget()
        self.formReadPage_3.setObjectName("formReadPage_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.formReadPage_3)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.clientEditButton_2 = QtWidgets.QPushButton(self.formReadPage_3)
        self.clientEditButton_2.setEnabled(False)
        self.clientEditButton_2.setMinimumSize(QtCore.QSize(97, 0))
        self.clientEditButton_2.setObjectName("clientEditButton_2")
        self.gridLayout_14.addWidget(self.clientEditButton_2, 2, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem10, 2, 0, 1, 2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.empPassportLabel = QtWidgets.QLabel(self.formReadPage_3)
        self.empPassportLabel.setMinimumSize(QtCore.QSize(0, 60))
        self.empPassportLabel.setText("")
        self.empPassportLabel.setObjectName("empPassportLabel")
        self.gridLayout_15.addWidget(self.empPassportLabel, 10, 0, 1, 3)
        self.label_22 = QtWidgets.QLabel(self.formReadPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_15.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.formReadPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_15.addWidget(self.label_20, 9, 0, 1, 3)
        self.empMiddlenameLabel = QtWidgets.QLabel(self.formReadPage_3)
        self.empMiddlenameLabel.setText("")
        self.empMiddlenameLabel.setObjectName("empMiddlenameLabel")
        self.gridLayout_15.addWidget(self.empMiddlenameLabel, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.formReadPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 3, 0, 1, 1)
        self.empEmpdateLabel = QtWidgets.QLabel(self.formReadPage_3)
        self.empEmpdateLabel.setText("")
        self.empEmpdateLabel.setObjectName("empEmpdateLabel")
        self.gridLayout_15.addWidget(self.empEmpdateLabel, 4, 1, 1, 1)
        self.empFirstnameLabel = QtWidgets.QLabel(self.formReadPage_3)
        self.empFirstnameLabel.setText("")
        self.empFirstnameLabel.setObjectName("empFirstnameLabel")
        self.gridLayout_15.addWidget(self.empFirstnameLabel, 1, 1, 1, 1)
        self.empBirthdateLabel = QtWidgets.QLabel(self.formReadPage_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.empBirthdateLabel.sizePolicy().hasHeightForWidth())
        self.empBirthdateLabel.setSizePolicy(sizePolicy)
        self.empBirthdateLabel.setText("")
        self.empBirthdateLabel.setWordWrap(True)
        self.empBirthdateLabel.setObjectName("empBirthdateLabel")
        self.gridLayout_15.addWidget(self.empBirthdateLabel, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.formReadPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_15.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.formReadPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_15.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.formReadPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 5, 0, 1, 1)
        self.empPhoneLabel = QtWidgets.QLabel(self.formReadPage_3)
        self.empPhoneLabel.setText("")
        self.empPhoneLabel.setObjectName("empPhoneLabel")
        self.gridLayout_15.addWidget(self.empPhoneLabel, 5, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.formReadPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_15.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.formReadPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_15.addWidget(self.label_33, 6, 0, 1, 1)
        self.empLastnameLabel = QtWidgets.QLabel(self.formReadPage_3)
        self.empLastnameLabel.setText("")
        self.empLastnameLabel.setObjectName("empLastnameLabel")
        self.gridLayout_15.addWidget(self.empLastnameLabel, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.formReadPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_15.addWidget(self.label_34, 7, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.formReadPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_15.addWidget(self.label_35, 8, 0, 1, 1)
        self.empShopLabel = QtWidgets.QLabel(self.formReadPage_3)
        self.empShopLabel.setText("")
        self.empShopLabel.setObjectName("empShopLabel")
        self.gridLayout_15.addWidget(self.empShopLabel, 6, 1, 1, 1)
        self.empDepartmentLabel = QtWidgets.QLabel(self.formReadPage_3)
        self.empDepartmentLabel.setText("")
        self.empDepartmentLabel.setObjectName("empDepartmentLabel")
        self.gridLayout_15.addWidget(self.empDepartmentLabel, 7, 1, 1, 1)
        self.empPositionLabel = QtWidgets.QLabel(self.formReadPage_3)
        self.empPositionLabel.setText("")
        self.empPositionLabel.setObjectName("empPositionLabel")
        self.gridLayout_15.addWidget(self.empPositionLabel, 8, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem11, 0, 2, 9, 1)
        self.gridLayout_14.addLayout(self.gridLayout_15, 0, 0, 2, 3)
        self.formStack_3.addWidget(self.formReadPage_3)
        self.formEditPage_3 = QtWidgets.QWidget()
        self.formEditPage_3.setObjectName("formEditPage_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.formEditPage_3)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem12 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem12, 5, 0, 1, 2)
        self.clientSaveButton_2 = QtWidgets.QPushButton(self.formEditPage_3)
        self.clientSaveButton_2.setObjectName("clientSaveButton_2")
        self.gridLayout_16.addWidget(self.clientSaveButton_2, 5, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(341, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem13, 2, 0, 1, 4)
        self.clientCancelButton_2 = QtWidgets.QPushButton(self.formEditPage_3)
        self.clientCancelButton_2.setObjectName("clientCancelButton_2")
        self.gridLayout_16.addWidget(self.clientCancelButton_2, 5, 3, 1, 1)
        self.clientPassportEdit_2 = QtWidgets.QPlainTextEdit(self.formEditPage_3)
        self.clientPassportEdit_2.setObjectName("clientPassportEdit_2")
        self.gridLayout_16.addWidget(self.clientPassportEdit_2, 4, 0, 1, 4)
        self.label_32 = QtWidgets.QLabel(self.formEditPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_16.addWidget(self.label_32, 3, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_28 = QtWidgets.QLabel(self.formEditPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_17.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.formEditPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_17.addWidget(self.label_26, 3, 0, 1, 1)
        self.clientLastnameEdit_2 = QtWidgets.QLineEdit(self.formEditPage_3)
        self.clientLastnameEdit_2.setObjectName("clientLastnameEdit_2")
        self.gridLayout_17.addWidget(self.clientLastnameEdit_2, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.formEditPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_17.addWidget(self.label_31, 4, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.formEditPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_17.addWidget(self.label_30, 5, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.formEditPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_17.addWidget(self.label_29, 0, 0, 1, 1)
        self.clientBirthdateEdit_2 = QtWidgets.QDateEdit(self.formEditPage_3)
        self.clientBirthdateEdit_2.setCalendarPopup(True)
        self.clientBirthdateEdit_2.setObjectName("clientBirthdateEdit_2")
        self.gridLayout_17.addWidget(self.clientBirthdateEdit_2, 3, 1, 1, 1)
        self.clientRegdateEdit_2 = QtWidgets.QDateEdit(self.formEditPage_3)
        self.clientRegdateEdit_2.setCalendarPopup(True)
        self.clientRegdateEdit_2.setObjectName("clientRegdateEdit_2")
        self.gridLayout_17.addWidget(self.clientRegdateEdit_2, 4, 1, 1, 1)
        self.clientMiddlenameEdit_2 = QtWidgets.QLineEdit(self.formEditPage_3)
        self.clientMiddlenameEdit_2.setObjectName("clientMiddlenameEdit_2")
        self.gridLayout_17.addWidget(self.clientMiddlenameEdit_2, 2, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.formEditPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_17.addWidget(self.label_37, 7, 0, 1, 1)
        self.clientFirstnameEdit_2 = QtWidgets.QLineEdit(self.formEditPage_3)
        self.clientFirstnameEdit_2.setObjectName("clientFirstnameEdit_2")
        self.gridLayout_17.addWidget(self.clientFirstnameEdit_2, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.formEditPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_17.addWidget(self.label_27, 1, 0, 1, 1)
        self.clientPhoneEdit_2 = QtWidgets.QLineEdit(self.formEditPage_3)
        self.clientPhoneEdit_2.setObjectName("clientPhoneEdit_2")
        self.gridLayout_17.addWidget(self.clientPhoneEdit_2, 5, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.formEditPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_17.addWidget(self.label_36, 6, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.formEditPage_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_17.addWidget(self.label_38, 8, 0, 1, 1)
        self.empDepartmentCombo = QtWidgets.QLineEdit(self.formEditPage_3)
        self.empDepartmentCombo.setObjectName("empDepartmentCombo")
        self.gridLayout_17.addWidget(self.empDepartmentCombo, 7, 1, 1, 1)
        self.empPositionCombo = QtWidgets.QLineEdit(self.formEditPage_3)
        self.empPositionCombo.setObjectName("empPositionCombo")
        self.gridLayout_17.addWidget(self.empPositionCombo, 8, 1, 1, 1)
        self.empShopCombo = QtWidgets.QComboBox(self.formEditPage_3)
        self.empShopCombo.setObjectName("empShopCombo")
        self.gridLayout_17.addWidget(self.empShopCombo, 6, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_17, 0, 0, 2, 4)
        self.formStack_3.addWidget(self.formEditPage_3)
        self.gridLayout_13.addWidget(self.formStack_3, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.stackedWidget.addWidget(self.page_employees)
        self.page_shops = QtWidgets.QWidget()
        self.page_shops.setObjectName("page_shops")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_shops)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_shops)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.carAddButton_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.carAddButton_2.setObjectName("carAddButton_2")
        self.gridLayout_18.addWidget(self.carAddButton_2, 1, 0, 1, 1)
        self.carDeleteButton_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.carDeleteButton_2.setObjectName("carDeleteButton_2")
        self.gridLayout_18.addWidget(self.carDeleteButton_2, 1, 1, 1, 1)
        self.shopListView = QtWidgets.QListView(self.groupBox_7)
        self.shopListView.setObjectName("shopListView")
        self.gridLayout_18.addWidget(self.shopListView, 0, 0, 1, 2)
        self.horizontalLayout_6.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_shops)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formStack_4 = QtWidgets.QStackedWidget(self.groupBox_8)
        self.formStack_4.setObjectName("formStack_4")
        self.formReadPage_4 = QtWidgets.QWidget()
        self.formReadPage_4.setObjectName("formReadPage_4")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.formReadPage_4)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.shopEditButton = QtWidgets.QPushButton(self.formReadPage_4)
        self.shopEditButton.setEnabled(False)
        self.shopEditButton.setMinimumSize(QtCore.QSize(97, 0))
        self.shopEditButton.setObjectName("shopEditButton")
        self.gridLayout_19.addWidget(self.shopEditButton, 3, 3, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem14, 3, 0, 1, 3)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem15, 2, 0, 1, 4)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_43 = QtWidgets.QLabel(self.formReadPage_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_20.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.formReadPage_4)
        self.label_39.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_20.addWidget(self.label_39, 0, 0, 1, 1)
        self.shopNameLabel = QtWidgets.QLabel(self.formReadPage_4)
        self.shopNameLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.shopNameLabel.setText("")
        self.shopNameLabel.setObjectName("shopNameLabel")
        self.gridLayout_20.addWidget(self.shopNameLabel, 0, 1, 1, 1)
        self.shopDescriptionLabel = QtWidgets.QLabel(self.formReadPage_4)
        self.shopDescriptionLabel.setText("")
        self.shopDescriptionLabel.setWordWrap(True)
        self.shopDescriptionLabel.setObjectName("shopDescriptionLabel")
        self.gridLayout_20.addWidget(self.shopDescriptionLabel, 4, 0, 1, 3)
        self.label_40 = QtWidgets.QLabel(self.formReadPage_4)
        self.label_40.setMinimumSize(QtCore.QSize(0, 0))
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_40.setObjectName("label_40")
        self.gridLayout_20.addWidget(self.label_40, 3, 0, 1, 3)
        self.label_44 = QtWidgets.QLabel(self.formReadPage_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_20.addWidget(self.label_44, 2, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem16, 0, 2, 3, 1)
        self.shopAddressLabel = QtWidgets.QLabel(self.formReadPage_4)
        self.shopAddressLabel.setText("")
        self.shopAddressLabel.setObjectName("shopAddressLabel")
        self.gridLayout_20.addWidget(self.shopAddressLabel, 1, 1, 1, 1)
        self.shopPhoneLabel = QtWidgets.QLabel(self.formReadPage_4)
        self.shopPhoneLabel.setText("")
        self.shopPhoneLabel.setObjectName("shopPhoneLabel")
        self.gridLayout_20.addWidget(self.shopPhoneLabel, 2, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_20, 0, 0, 2, 4)
        self.formStack_4.addWidget(self.formReadPage_4)
        self.formEditPage_4 = QtWidgets.QWidget()
        self.formEditPage_4.setObjectName("formEditPage_4")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.formEditPage_4)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.shopSaveButton = QtWidgets.QPushButton(self.formEditPage_4)
        self.shopSaveButton.setObjectName("shopSaveButton")
        self.gridLayout_21.addWidget(self.shopSaveButton, 2, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem17, 2, 0, 1, 2)
        self.shopCancelButton = QtWidgets.QPushButton(self.formEditPage_4)
        self.shopCancelButton.setObjectName("shopCancelButton")
        self.gridLayout_21.addWidget(self.shopCancelButton, 2, 3, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_45 = QtWidgets.QLabel(self.formEditPage_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_22.addWidget(self.label_45, 1, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.formEditPage_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_22.addWidget(self.label_46, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.formEditPage_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_22.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.formEditPage_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_42.setObjectName("label_42")
        self.gridLayout_22.addWidget(self.label_42, 3, 0, 1, 3)
        self.shopDescriotionEdit = QtWidgets.QPlainTextEdit(self.formEditPage_4)
        self.shopDescriotionEdit.setObjectName("shopDescriotionEdit")
        self.gridLayout_22.addWidget(self.shopDescriotionEdit, 4, 0, 1, 3)
        self.shopPhoneEdit = QtWidgets.QLineEdit(self.formEditPage_4)
        self.shopPhoneEdit.setObjectName("shopPhoneEdit")
        self.gridLayout_22.addWidget(self.shopPhoneEdit, 2, 1, 1, 1)
        self.shopAddressEdit = QtWidgets.QLineEdit(self.formEditPage_4)
        self.shopAddressEdit.setObjectName("shopAddressEdit")
        self.gridLayout_22.addWidget(self.shopAddressEdit, 1, 1, 1, 2)
        self.shopNameEdit = QtWidgets.QLineEdit(self.formEditPage_4)
        self.shopNameEdit.setObjectName("shopNameEdit")
        self.gridLayout_22.addWidget(self.shopNameEdit, 0, 1, 1, 2)
        self.gridLayout_21.addLayout(self.gridLayout_22, 0, 0, 2, 4)
        self.formStack_4.addWidget(self.formEditPage_4)
        self.horizontalLayout_5.addWidget(self.formStack_4)
        self.horizontalLayout_6.addWidget(self.groupBox_8)
        self.stackedWidget.addWidget(self.page_shops)
        self.page_details = QtWidgets.QWidget()
        self.page_details.setObjectName("page_details")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_details)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_details)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.carAddButton_3 = QtWidgets.QPushButton(self.groupBox_9)
        self.carAddButton_3.setObjectName("carAddButton_3")
        self.gridLayout_23.addWidget(self.carAddButton_3, 1, 0, 1, 1)
        self.carDeleteButton_3 = QtWidgets.QPushButton(self.groupBox_9)
        self.carDeleteButton_3.setObjectName("carDeleteButton_3")
        self.gridLayout_23.addWidget(self.carDeleteButton_3, 1, 1, 1, 1)
        self.detailListView = QtWidgets.QListView(self.groupBox_9)
        self.detailListView.setObjectName("detailListView")
        self.gridLayout_23.addWidget(self.detailListView, 0, 0, 1, 2)
        self.horizontalLayout_8.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.page_details)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formStack_5 = QtWidgets.QStackedWidget(self.groupBox_10)
        self.formStack_5.setObjectName("formStack_5")
        self.formReadPage_5 = QtWidgets.QWidget()
        self.formReadPage_5.setObjectName("formReadPage_5")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.formReadPage_5)
        self.gridLayout_24.setObjectName("gridLayout_24")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem18, 3, 0, 1, 3)
        self.detailPhotoLabel = QtWidgets.QLabel(self.formReadPage_5)
        self.detailPhotoLabel.setMinimumSize(QtCore.QSize(160, 160))
        self.detailPhotoLabel.setMaximumSize(QtCore.QSize(160, 160))
        self.detailPhotoLabel.setStyleSheet("border: 1px solid;")
        self.detailPhotoLabel.setText("")
        self.detailPhotoLabel.setIndent(-1)
        self.detailPhotoLabel.setObjectName("detailPhotoLabel")
        self.gridLayout_24.addWidget(self.detailPhotoLabel, 0, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem19, 4, 0, 1, 1)
        self.shopEditButton_2 = QtWidgets.QPushButton(self.formReadPage_5)
        self.shopEditButton_2.setEnabled(False)
        self.shopEditButton_2.setMinimumSize(QtCore.QSize(97, 0))
        self.shopEditButton_2.setObjectName("shopEditButton_2")
        self.gridLayout_24.addWidget(self.shopEditButton_2, 4, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.formReadPage_5)
        self.label_49.setMinimumSize(QtCore.QSize(0, 0))
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_49.setObjectName("label_49")
        self.gridLayout_24.addWidget(self.label_49, 1, 0, 1, 1)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.detailNameLabel = QtWidgets.QLabel(self.formReadPage_5)
        self.detailNameLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.detailNameLabel.setText("")
        self.detailNameLabel.setObjectName("detailNameLabel")
        self.gridLayout_25.addWidget(self.detailNameLabel, 0, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.formReadPage_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_25.addWidget(self.label_55, 3, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.formReadPage_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_25.addWidget(self.label_50, 2, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.formReadPage_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_25.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.formReadPage_5)
        self.label_48.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_25.addWidget(self.label_48, 0, 0, 1, 1)
        self.detailArticleLabel = QtWidgets.QLabel(self.formReadPage_5)
        self.detailArticleLabel.setText("")
        self.detailArticleLabel.setObjectName("detailArticleLabel")
        self.gridLayout_25.addWidget(self.detailArticleLabel, 1, 1, 1, 1)
        self.detailCategoryLabel = QtWidgets.QLabel(self.formReadPage_5)
        self.detailCategoryLabel.setText("")
        self.detailCategoryLabel.setObjectName("detailCategoryLabel")
        self.gridLayout_25.addWidget(self.detailCategoryLabel, 2, 1, 1, 1)
        self.detailWarrantyLabel = QtWidgets.QLabel(self.formReadPage_5)
        self.detailWarrantyLabel.setText("")
        self.detailWarrantyLabel.setObjectName("detailWarrantyLabel")
        self.gridLayout_25.addWidget(self.detailWarrantyLabel, 3, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.formReadPage_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_67.setObjectName("label_67")
        self.gridLayout_25.addWidget(self.label_67, 4, 0, 1, 1)
        self.detailPriceLabel = QtWidgets.QLabel(self.formReadPage_5)
        self.detailPriceLabel.setText("")
        self.detailPriceLabel.setObjectName("detailPriceLabel")
        self.gridLayout_25.addWidget(self.detailPriceLabel, 4, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem20, 0, 2, 5, 1)
        self.gridLayout_24.addLayout(self.gridLayout_25, 0, 0, 1, 1)
        self.detailDescriptionLabel = QtWidgets.QLabel(self.formReadPage_5)
        self.detailDescriptionLabel.setText("")
        self.detailDescriptionLabel.setWordWrap(True)
        self.detailDescriptionLabel.setObjectName("detailDescriptionLabel")
        self.gridLayout_24.addWidget(self.detailDescriptionLabel, 2, 0, 1, 1)
        self.formStack_5.addWidget(self.formReadPage_5)
        self.formEditPage_5 = QtWidgets.QWidget()
        self.formEditPage_5.setObjectName("formEditPage_5")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.formEditPage_5)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.detailDeletePhotoButton = QtWidgets.QPushButton(self.formEditPage_5)
        self.detailDeletePhotoButton.setObjectName("detailDeletePhotoButton")
        self.gridLayout_26.addWidget(self.detailDeletePhotoButton, 2, 4, 1, 1)
        self.detailBrowsePhotoButton = QtWidgets.QPushButton(self.formEditPage_5)
        self.detailBrowsePhotoButton.setObjectName("detailBrowsePhotoButton")
        self.gridLayout_26.addWidget(self.detailBrowsePhotoButton, 2, 3, 1, 1)
        self.detailDescriptionEdit = QtWidgets.QPlainTextEdit(self.formEditPage_5)
        self.detailDescriptionEdit.setObjectName("detailDescriptionEdit")
        self.gridLayout_26.addWidget(self.detailDescriptionEdit, 3, 0, 1, 6)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_51 = QtWidgets.QLabel(self.formEditPage_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_27.addWidget(self.label_51, 1, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.formEditPage_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_27.addWidget(self.label_52, 2, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.formEditPage_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_27.addWidget(self.label_53, 0, 0, 1, 1)
        self.detailArticleEdit = QtWidgets.QLineEdit(self.formEditPage_5)
        self.detailArticleEdit.setObjectName("detailArticleEdit")
        self.gridLayout_27.addWidget(self.detailArticleEdit, 1, 1, 1, 2)
        self.detailNameEdit = QtWidgets.QLineEdit(self.formEditPage_5)
        self.detailNameEdit.setObjectName("detailNameEdit")
        self.gridLayout_27.addWidget(self.detailNameEdit, 0, 1, 1, 2)
        self.detailCategoryEdit = QtWidgets.QLineEdit(self.formEditPage_5)
        self.detailCategoryEdit.setObjectName("detailCategoryEdit")
        self.gridLayout_27.addWidget(self.detailCategoryEdit, 2, 1, 1, 2)
        self.detailWarrantyEdit = QtWidgets.QLineEdit(self.formEditPage_5)
        self.detailWarrantyEdit.setObjectName("detailWarrantyEdit")
        self.gridLayout_27.addWidget(self.detailWarrantyEdit, 3, 1, 2, 2)
        self.label_56 = QtWidgets.QLabel(self.formEditPage_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_27.addWidget(self.label_56, 3, 0, 2, 1)
        self.label_68 = QtWidgets.QLabel(self.formEditPage_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_27.addWidget(self.label_68, 5, 0, 1, 1)
        self.detailPriceEdit = QtWidgets.QLineEdit(self.formEditPage_5)
        self.detailPriceEdit.setObjectName("detailPriceEdit")
        self.gridLayout_27.addWidget(self.detailPriceEdit, 5, 1, 1, 2)
        self.gridLayout_26.addLayout(self.gridLayout_27, 0, 0, 1, 2)
        self.shopSaveButton_2 = QtWidgets.QPushButton(self.formEditPage_5)
        self.shopSaveButton_2.setObjectName("shopSaveButton_2")
        self.gridLayout_26.addWidget(self.shopSaveButton_2, 4, 1, 1, 3)
        spacerItem21 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem21, 4, 0, 1, 1)
        self.shopCancelButton_2 = QtWidgets.QPushButton(self.formEditPage_5)
        self.shopCancelButton_2.setObjectName("shopCancelButton_2")
        self.gridLayout_26.addWidget(self.shopCancelButton_2, 4, 4, 1, 2)
        self.label_54 = QtWidgets.QLabel(self.formEditPage_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_54.setObjectName("label_54")
        self.gridLayout_26.addWidget(self.label_54, 2, 0, 1, 1)
        self.carPhotoLabel_4 = QtWidgets.QLabel(self.formEditPage_5)
        self.carPhotoLabel_4.setMinimumSize(QtCore.QSize(160, 160))
        self.carPhotoLabel_4.setMaximumSize(QtCore.QSize(160, 160))
        self.carPhotoLabel_4.setStyleSheet("border: 1px solid;")
        self.carPhotoLabel_4.setText("")
        self.carPhotoLabel_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.carPhotoLabel_4.setIndent(-1)
        self.carPhotoLabel_4.setObjectName("carPhotoLabel_4")
        self.gridLayout_26.addWidget(self.carPhotoLabel_4, 0, 3, 2, 3)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem22, 0, 2, 1, 1)
        self.formStack_5.addWidget(self.formEditPage_5)
        self.horizontalLayout_7.addWidget(self.formStack_5)
        self.horizontalLayout_8.addWidget(self.groupBox_10)
        self.stackedWidget.addWidget(self.page_details)
        self.page_warehouse = QtWidgets.QWidget()
        self.page_warehouse.setObjectName("page_warehouse")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_warehouse)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_11 = QtWidgets.QGroupBox(self.page_warehouse)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.detailShopListView = QtWidgets.QListView(self.groupBox_11)
        self.detailShopListView.setObjectName("detailShopListView")
        self.gridLayout_28.addWidget(self.detailShopListView, 0, 0, 1, 2)
        self.horizontalLayout_9.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.page_warehouse)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.warehouseTableView = QtWidgets.QTableView(self.groupBox_12)
        self.warehouseTableView.setObjectName("warehouseTableView")
        self.verticalLayout_2.addWidget(self.warehouseTableView)
        self.horizontalLayout_9.addWidget(self.groupBox_12)
        self.stackedWidget.addWidget(self.page_warehouse)
        self.page_cardetails = QtWidgets.QWidget()
        self.page_cardetails.setObjectName("page_cardetails")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_cardetails)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_13 = QtWidgets.QGroupBox(self.page_cardetails)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.carListView_2 = QtWidgets.QListView(self.groupBox_13)
        self.carListView_2.setObjectName("carListView_2")
        self.gridLayout_29.addWidget(self.carListView_2, 0, 0, 1, 2)
        self.horizontalLayout_10.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.page_cardetails)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.carDetailAddButton = QtWidgets.QPushButton(self.groupBox_14)
        self.carDetailAddButton.setObjectName("carDetailAddButton")
        self.gridLayout_30.addWidget(self.carDetailAddButton, 1, 0, 1, 1)
        self.carDetailDeleteButton = QtWidgets.QPushButton(self.groupBox_14)
        self.carDetailDeleteButton.setObjectName("carDetailDeleteButton")
        self.gridLayout_30.addWidget(self.carDetailDeleteButton, 1, 1, 1, 1)
        self.carDetailListView = QtWidgets.QTableView(self.groupBox_14)
        self.carDetailListView.setObjectName("carDetailListView")
        self.gridLayout_30.addWidget(self.carDetailListView, 0, 0, 1, 2)
        self.horizontalLayout_10.addWidget(self.groupBox_14)
        self.stackedWidget.addWidget(self.page_cardetails)
        self.page_orders = QtWidgets.QWidget()
        self.page_orders.setObjectName("page_orders")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.page_orders)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.groupBox_15 = QtWidgets.QGroupBox(self.page_orders)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.ordersListView = QtWidgets.QListView(self.groupBox_15)
        self.ordersListView.setObjectName("ordersListView")
        self.gridLayout_31.addWidget(self.ordersListView, 0, 0, 1, 2)
        self.gridLayout_37.addWidget(self.groupBox_15, 0, 0, 2, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.page_orders)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formStack_6 = QtWidgets.QStackedWidget(self.groupBox_16)
        self.formStack_6.setObjectName("formStack_6")
        self.formReadPage_6 = QtWidgets.QWidget()
        self.formReadPage_6.setObjectName("formReadPage_6")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.formReadPage_6)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem23, 2, 0, 1, 2)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.label_57 = QtWidgets.QLabel(self.formReadPage_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_33.addWidget(self.label_57, 1, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.formReadPage_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_59.setObjectName("label_59")
        self.gridLayout_33.addWidget(self.label_59, 3, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.formReadPage_6)
        self.label_58.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_33.addWidget(self.label_58, 0, 0, 1, 1)
        self.orderManagerLabel = QtWidgets.QLabel(self.formReadPage_6)
        self.orderManagerLabel.setText("")
        self.orderManagerLabel.setObjectName("orderManagerLabel")
        self.gridLayout_33.addWidget(self.orderManagerLabel, 2, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.formReadPage_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout_33.addWidget(self.label_60, 2, 0, 1, 1)
        self.orderShopLabel = QtWidgets.QLabel(self.formReadPage_6)
        self.orderShopLabel.setText("")
        self.orderShopLabel.setObjectName("orderShopLabel")
        self.gridLayout_33.addWidget(self.orderShopLabel, 1, 1, 1, 1)
        self.orderClientLabel = QtWidgets.QLabel(self.formReadPage_6)
        self.orderClientLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.orderClientLabel.setText("")
        self.orderClientLabel.setObjectName("orderClientLabel")
        self.gridLayout_33.addWidget(self.orderClientLabel, 0, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.formReadPage_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName("label_65")
        self.gridLayout_33.addWidget(self.label_65, 4, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem24, 0, 2, 5, 1)
        self.orderDateLabel = QtWidgets.QLabel(self.formReadPage_6)
        self.orderDateLabel.setText("")
        self.orderDateLabel.setObjectName("orderDateLabel")
        self.gridLayout_33.addWidget(self.orderDateLabel, 3, 1, 1, 1)
        self.orderPriceLabel = QtWidgets.QLabel(self.formReadPage_6)
        self.orderPriceLabel.setText("")
        self.orderPriceLabel.setObjectName("orderPriceLabel")
        self.gridLayout_33.addWidget(self.orderPriceLabel, 4, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_33, 0, 0, 2, 3)
        self.shopEditButton_3 = QtWidgets.QPushButton(self.formReadPage_6)
        self.shopEditButton_3.setEnabled(False)
        self.shopEditButton_3.setMinimumSize(QtCore.QSize(97, 0))
        self.shopEditButton_3.setObjectName("shopEditButton_3")
        self.gridLayout_32.addWidget(self.shopEditButton_3, 2, 2, 1, 1)
        self.formStack_6.addWidget(self.formReadPage_6)
        self.formEditPage_6 = QtWidgets.QWidget()
        self.formEditPage_6.setObjectName("formEditPage_6")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.formEditPage_6)
        self.gridLayout_34.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.shopSaveButton_3 = QtWidgets.QPushButton(self.formEditPage_6)
        self.shopSaveButton_3.setObjectName("shopSaveButton_3")
        self.gridLayout_34.addWidget(self.shopSaveButton_3, 2, 2, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem25, 2, 0, 1, 2)
        self.shopCancelButton_3 = QtWidgets.QPushButton(self.formEditPage_6)
        self.shopCancelButton_3.setObjectName("shopCancelButton_3")
        self.gridLayout_34.addWidget(self.shopCancelButton_3, 2, 3, 1, 1)
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.label_63 = QtWidgets.QLabel(self.formEditPage_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_35.addWidget(self.label_63, 0, 0, 1, 1)
        self.orderManagerEdit = QtWidgets.QLineEdit(self.formEditPage_6)
        self.orderManagerEdit.setObjectName("orderManagerEdit")
        self.gridLayout_35.addWidget(self.orderManagerEdit, 2, 1, 1, 1)
        self.orderClientEdit = QtWidgets.QLineEdit(self.formEditPage_6)
        self.orderClientEdit.setObjectName("orderClientEdit")
        self.gridLayout_35.addWidget(self.orderClientEdit, 0, 1, 1, 2)
        self.label_61 = QtWidgets.QLabel(self.formEditPage_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_61.setObjectName("label_61")
        self.gridLayout_35.addWidget(self.label_61, 1, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.formEditPage_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_35.addWidget(self.label_62, 2, 0, 1, 1)
        self.orderShopEdit = QtWidgets.QLineEdit(self.formEditPage_6)
        self.orderShopEdit.setObjectName("orderShopEdit")
        self.gridLayout_35.addWidget(self.orderShopEdit, 1, 1, 1, 2)
        self.label_64 = QtWidgets.QLabel(self.formEditPage_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_35.addWidget(self.label_64, 3, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.formEditPage_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_66.setObjectName("label_66")
        self.gridLayout_35.addWidget(self.label_66, 4, 0, 1, 1)
        self.orderDateEdit = QtWidgets.QLineEdit(self.formEditPage_6)
        self.orderDateEdit.setObjectName("orderDateEdit")
        self.gridLayout_35.addWidget(self.orderDateEdit, 3, 1, 1, 1)
        self.orderPriceEdit = QtWidgets.QLineEdit(self.formEditPage_6)
        self.orderPriceEdit.setReadOnly(True)
        self.orderPriceEdit.setObjectName("orderPriceEdit")
        self.gridLayout_35.addWidget(self.orderPriceEdit, 4, 1, 1, 1)
        self.gridLayout_34.addLayout(self.gridLayout_35, 0, 0, 2, 4)
        self.formStack_6.addWidget(self.formEditPage_6)
        self.verticalLayout_3.addWidget(self.formStack_6)
        self.gridLayout_37.addWidget(self.groupBox_16, 0, 1, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.page_orders)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.tableView = QtWidgets.QTableView(self.groupBox_17)
        self.tableView.setMinimumSize(QtCore.QSize(0, 173))
        self.tableView.setObjectName("tableView")
        self.gridLayout_36.addWidget(self.tableView, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_36.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_36.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.gridLayout_37.addWidget(self.groupBox_17, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_orders)
        self.horizontalLayout_11.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 29))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.view_clients = QtWidgets.QAction(MainWindow)
        self.view_clients.setCheckable(True)
        self.view_clients.setChecked(True)
        self.view_clients.setObjectName("view_clients")
        self.view_employees = QtWidgets.QAction(MainWindow)
        self.view_employees.setCheckable(True)
        self.view_employees.setObjectName("view_employees")
        self.view_shops = QtWidgets.QAction(MainWindow)
        self.view_shops.setCheckable(True)
        self.view_shops.setObjectName("view_shops")
        self.view_details = QtWidgets.QAction(MainWindow)
        self.view_details.setCheckable(True)
        self.view_details.setObjectName("view_details")
        self.view_cars = QtWidgets.QAction(MainWindow)
        self.view_cars.setCheckable(True)
        self.view_cars.setObjectName("view_cars")
        self.view_warehouse = QtWidgets.QAction(MainWindow)
        self.view_warehouse.setCheckable(True)
        self.view_warehouse.setObjectName("view_warehouse")
        self.view_cardetails = QtWidgets.QAction(MainWindow)
        self.view_cardetails.setCheckable(True)
        self.view_cardetails.setObjectName("view_cardetails")
        self.view_orders = QtWidgets.QAction(MainWindow)
        self.view_orders.setCheckable(True)
        self.view_orders.setObjectName("view_orders")
        self.file_quit = QtWidgets.QAction(MainWindow)
        self.file_quit.setObjectName("file_quit")
        self.menu.addAction(self.file_quit)
        self.menu_2.addAction(self.view_clients)
        self.menu_2.addAction(self.view_orders)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.view_employees)
        self.menu_2.addAction(self.view_shops)
        self.menu_2.addAction(self.view_warehouse)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.view_details)
        self.menu_2.addAction(self.view_cars)
        self.menu_2.addAction(self.view_cardetails)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.view_clients)
        self.toolBar.addAction(self.view_orders)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.view_employees)
        self.toolBar.addAction(self.view_shops)
        self.toolBar.addAction(self.view_warehouse)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.view_details)
        self.toolBar.addAction(self.view_cars)
        self.toolBar.addAction(self.view_cardetails)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.formStack.setCurrentIndex(0)
        self.clientStack.setCurrentIndex(0)
        self.formStack_3.setCurrentIndex(0)
        self.formStack_4.setCurrentIndex(0)
        self.formStack_5.setCurrentIndex(0)
        self.formStack_6.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лада Деталь"))
        self.groupBox.setTitle(_translate("MainWindow", "Модели"))
        self.carAddButton.setText(_translate("MainWindow", "Добавить"))
        self.carDeleteButton.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Информация"))
        self.carEditButton.setText(_translate("MainWindow", "Редактировать"))
        self.label.setText(_translate("MainWindow", "Название:"))
        self.label_3.setText(_translate("MainWindow", "Описание:"))
        self.carSaveButton.setText(_translate("MainWindow", "Сохранить"))
        self.carCancelButton.setText(_translate("MainWindow", "Отменить"))
        self.label_2.setText(_translate("MainWindow", "Название:"))
        self.label_4.setText(_translate("MainWindow", "Описание:"))
        self.carDeletePhotoButton.setText(_translate("MainWindow", "Удалить"))
        self.carBrowsePhotoButton.setText(_translate("MainWindow", "Обзор..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Клиенты"))
        self.clientAddButton.setText(_translate("MainWindow", "Добавить"))
        self.clientDeleteButton.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Анкета"))
        self.clientEditButton.setText(_translate("MainWindow", "Редактировать"))
        self.label_5.setText(_translate("MainWindow", "Имя:"))
        self.label_17.setText(_translate("MainWindow", "Паспортные данные:"))
        self.label_9.setText(_translate("MainWindow", "Дата рег.:"))
        self.label_6.setText(_translate("MainWindow", "Отчество:"))
        self.label_7.setText(_translate("MainWindow", "Фамилия:"))
        self.label_11.setText(_translate("MainWindow", "Телефон:"))
        self.label_8.setText(_translate("MainWindow", "Дата рожд.:"))
        self.label_69.setText(_translate("MainWindow", "Email:"))
        self.clientSaveButton.setText(_translate("MainWindow", "Сохранить"))
        self.clientCancelButton.setText(_translate("MainWindow", "Отменить"))
        self.label_18.setText(_translate("MainWindow", "Паспортные данные:"))
        self.label_15.setText(_translate("MainWindow", "Дата рожд.:"))
        self.label_14.setText(_translate("MainWindow", "Имя:"))
        self.label_13.setText(_translate("MainWindow", "Отчество:"))
        self.label_16.setText(_translate("MainWindow", "Фамилия:"))
        self.label_12.setText(_translate("MainWindow", "Телефон:"))
        self.label_10.setText(_translate("MainWindow", "Дата рег.:"))
        self.clientBirthdateEdit.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.clientRegdateEdit.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.label_70.setText(_translate("MainWindow", "Email:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Сотрудники"))
        self.clientAddButton_2.setText(_translate("MainWindow", "Добавить"))
        self.clientDeleteButton_2.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Анкета"))
        self.clientEditButton_2.setText(_translate("MainWindow", "Редактировать"))
        self.label_22.setText(_translate("MainWindow", "Отчество:"))
        self.label_20.setText(_translate("MainWindow", "Паспортные данные:"))
        self.label_25.setText(_translate("MainWindow", "Дата рожд.:"))
        self.label_19.setText(_translate("MainWindow", "Имя:"))
        self.label_21.setText(_translate("MainWindow", "Дата труд-ва:"))
        self.label_24.setText(_translate("MainWindow", "Телефон:"))
        self.label_23.setText(_translate("MainWindow", "Фамилия:"))
        self.label_33.setText(_translate("MainWindow", "Магазин:"))
        self.label_34.setText(_translate("MainWindow", "Отдел:"))
        self.label_35.setText(_translate("MainWindow", "Должность:"))
        self.clientSaveButton_2.setText(_translate("MainWindow", "Сохранить"))
        self.clientCancelButton_2.setText(_translate("MainWindow", "Отменить"))
        self.label_32.setText(_translate("MainWindow", "Паспортные данные:"))
        self.label_28.setText(_translate("MainWindow", "Отчество:"))
        self.label_26.setText(_translate("MainWindow", "Дата рожд.:"))
        self.label_31.setText(_translate("MainWindow", "Дата труд-ва:"))
        self.label_30.setText(_translate("MainWindow", "Телефон:"))
        self.label_29.setText(_translate("MainWindow", "Фамилия:"))
        self.clientBirthdateEdit_2.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.clientRegdateEdit_2.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.label_37.setText(_translate("MainWindow", "Отдел:"))
        self.label_27.setText(_translate("MainWindow", "Имя:"))
        self.label_36.setText(_translate("MainWindow", "Магазин:"))
        self.label_38.setText(_translate("MainWindow", "Должность:"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Магазины"))
        self.carAddButton_2.setText(_translate("MainWindow", "Добавить"))
        self.carDeleteButton_2.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Информация"))
        self.shopEditButton.setText(_translate("MainWindow", "Редактировать"))
        self.label_43.setText(_translate("MainWindow", "Адрес:"))
        self.label_39.setText(_translate("MainWindow", "Название:"))
        self.label_40.setText(_translate("MainWindow", "Описание:"))
        self.label_44.setText(_translate("MainWindow", "Телефон:"))
        self.shopSaveButton.setText(_translate("MainWindow", "Сохранить"))
        self.shopCancelButton.setText(_translate("MainWindow", "Отменить"))
        self.label_45.setText(_translate("MainWindow", "Адрес:"))
        self.label_46.setText(_translate("MainWindow", "Телефон:"))
        self.label_41.setText(_translate("MainWindow", "Название:"))
        self.label_42.setText(_translate("MainWindow", "Описание:"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Запчасти"))
        self.carAddButton_3.setText(_translate("MainWindow", "Добавить"))
        self.carDeleteButton_3.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Информация"))
        self.shopEditButton_2.setText(_translate("MainWindow", "Редактировать"))
        self.label_49.setText(_translate("MainWindow", "Описание:"))
        self.label_55.setText(_translate("MainWindow", "Гарантия:"))
        self.label_50.setText(_translate("MainWindow", "Категория:"))
        self.label_47.setText(_translate("MainWindow", "Артикул:"))
        self.label_48.setText(_translate("MainWindow", "Наименование:"))
        self.label_67.setText(_translate("MainWindow", "Цена:"))
        self.detailDeletePhotoButton.setText(_translate("MainWindow", "Удалить"))
        self.detailBrowsePhotoButton.setText(_translate("MainWindow", "Обзор..."))
        self.label_51.setText(_translate("MainWindow", "Артикул:"))
        self.label_52.setText(_translate("MainWindow", "Категория:"))
        self.label_53.setText(_translate("MainWindow", "Наименование:"))
        self.label_56.setText(_translate("MainWindow", "Гарантия:"))
        self.label_68.setText(_translate("MainWindow", "Цена:"))
        self.shopSaveButton_2.setText(_translate("MainWindow", "Сохранить"))
        self.shopCancelButton_2.setText(_translate("MainWindow", "Отменить"))
        self.label_54.setText(_translate("MainWindow", "Описание:"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Магазины"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Склад магазина"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Модели авто"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Подходящие запчасти"))
        self.carDetailAddButton.setText(_translate("MainWindow", "Добавить"))
        self.carDetailDeleteButton.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Заказы"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Информация о заказе"))
        self.label_57.setText(_translate("MainWindow", "Магазин:"))
        self.label_59.setText(_translate("MainWindow", "Дата:"))
        self.label_58.setText(_translate("MainWindow", "Клиент:"))
        self.label_60.setText(_translate("MainWindow", "Менеджер:"))
        self.label_65.setText(_translate("MainWindow", "Цена:"))
        self.shopEditButton_3.setText(_translate("MainWindow", "Редактировать"))
        self.shopSaveButton_3.setText(_translate("MainWindow", "Сохранить"))
        self.shopCancelButton_3.setText(_translate("MainWindow", "Отменить"))
        self.label_63.setText(_translate("MainWindow", "Клиент:"))
        self.label_61.setText(_translate("MainWindow", "Магазин:"))
        self.label_62.setText(_translate("MainWindow", "Менеджер:"))
        self.label_64.setText(_translate("MainWindow", "Дата:"))
        self.label_66.setText(_translate("MainWindow", "Цена:"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Состав заказа"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.setText(_translate("MainWindow", "Удалить"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Формы"))
        self.menu_3.setTitle(_translate("MainWindow", "Отчёты"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.view_clients.setText(_translate("MainWindow", "Клиенты"))
        self.view_employees.setText(_translate("MainWindow", "Сотрудники"))
        self.view_shops.setText(_translate("MainWindow", "Магазины"))
        self.view_details.setText(_translate("MainWindow", "Запчасти"))
        self.view_cars.setText(_translate("MainWindow", "Машины"))
        self.view_warehouse.setText(_translate("MainWindow", "Склад"))
        self.view_cardetails.setText(_translate("MainWindow", "Комплектующие"))
        self.view_orders.setText(_translate("MainWindow", "Заказы"))
        self.file_quit.setText(_translate("MainWindow", "Выход"))

